[project]
name = "practicalcrypto2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Carlos Ortiz", email = "cortizm1@jh.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
]

[project.scripts]
practicalcrypto2026 = "practicalcrypto2026:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
